version: "2.2"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: yarn run watch
    environment:
      - NOMICS_API_KEY=${NOMICS_API_KEY} 
      - BITTREX_API_KEY=${BITTREX_API_KEY}
      - BITTREX_API_SECRET=${BITTREX_API_SECRET}  
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_DATABASE_TESTING=${MYSQL_DATABASE_TESTING}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - NODE_ENV=development
      - LOG_LEVEL=info
    ports:
      - "3800:4000"
      - "9229:9229"
    volumes:
      - ./api:/api
    depends_on:
      - mysql
    mem_limit: 1g
    memswap_limit: 3g
    cpuset: 0,1
    cpus: ".5"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    mem_limit: 1g
    memswap_limit: 3g
    cpuset: 0,1
    cpus: ".5"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_LIMIT=2G
    ports:
      - "8082:80"
    expose: 
      - "80"
    volumes:
      - /sessions
      - ./phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    depends_on:
      - mysql

volumes:
  mysqldata:
    driver: "local"