version: "2"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: 
      [sh, -c, "yarn run prod-start & npm run forever && tail -F anything"]
    environment:
      - NOMICS_API_KEY=${NOMICS_API_KEY}
      - BITTREX_API_KEY=${BITTREX_API_KEY}
      - BITTREX_API_SECRET=${BITTREX_API_SECRET}  
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_DATABASE_TESTING=${MYSQL_DATABASE_TESTING}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD_PROD}
      - NODE_ENV=development
      - LOG_LEVEL=warn
    ports:
      - "80:4000"
      - "443:4000"
    volumes:
      - ./api:/api
      - /logs/api:/api/logs
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_PROD}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD_PROD}
      - UPLOAD_LIMIT=200000000
    ports:
      - "8080:80"
    expose: 
      - "80"
    volumes:
      - /sessions
    depends_on:
      - mysql

volumes:
  mysqldata:
    driver: "local"