
CREATE TABLE IF NOT EXISTS `log_entry` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `currencies_saved` SMALLINT(5) UNSIGNED DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,

 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3;
