
CREATE TABLE IF NOT EXISTS `data_ages` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datetime` timestamp DEFAULT CURRENT_TIMESTAMP,
  `crunched_min` SMALLINT UNSIGNED DEFAULT NULL,
  `crunched_max` SMALLINT UNSIGNED DEFAULT NULL,
  `crunched_average` SMALLINT UNSIGNED DEFAULT NULL,

 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3;
