name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install deps
        run: cd ./api && yarn
      
      - name: Server starts
        run: cd ./api && yarn run start-server