name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install deps
        run: yarn
        working-directory: ./api
      
      - name: Build dependencies
        run: yarn run build
        working-directory: ./api